# fly.toml app configuration file generated for hyperliquid-alerts on 2025-10-18T16:47:19-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hyperliquid-alerts'
primary_region = 'lax'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/data/seen.db'
  HYPERLIQUID_API = 'https://api.hyperliquid.xyz/info'
  HYPURR_BASE = 'https://hypurrscan.io'
  LOOKBACK_MINUTES = '10'
  VIP_LOOKBACK_HOURS = '48'
  POLL_SECONDS = '30'
  USD_DEPOSIT_THRESHOLD = '20000000'
  USD_SHORT_THRESHOLD = '25000000'
  WEBHOOK_TARGET = 'slack'
  CLUSTER_DETECTION_ENABLED = 'true'
  CLUSTER_TIME_WINDOW_MINUTES = '60'
  CLUSTER_MIN_SCORE = '70'
  CLUSTER_MIN_NOTIONAL = '50000000'
  MARKET_SCAN_TOKENS = 'BTC,ETH'
  MARKET_MIN_TRADE_SIZE = '5000000'

[[mounts]]
  source = 'alertvol'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
